Homework 1
infinum-academy/js-react-academy-2024-mominik15 pull request #1
Opened 2024-07-03 22:41 UTC by mominik15

- Created the main page for TV Show App, displaying a show called 'Dark'. There's an image of the show with a description and average rating.
- Enabled adding a new review: it is possible to enter a textual description and select a number of stars for a rating.
- Listed all current reviews. Also, enabled deleting of the reviews.

2024-07-04 14:01 UTC, ante-pesorda commented on tv_shows/index.html
> +        <link rel="stylesheet" href="styles.css">
dodati favicon

2024-07-04 14:08 UTC, ante-pesorda requested changes
Samo radi higijene korisnikovog browsera, ne bi trebali kreirati localStorage item prije dodavanja prvo reviewa, odnosno trebali bi ga brisat nakon brisanja zadnjeg

2024-07-04 14:08 UTC, ante-pesorda commented on tv_shows/index.html
> +            <div id="reviews">
Za ovo Stjepka krivi, od njega smo ovo pokupili 😄 
Između multiline blokova stavimo malo prostora, da bude čitljivije
```suggestion
            </div>

            <div id="reviews">
```

2024-07-04 14:08 UTC, ante-pesorda commented on tv_shows/index.html
> +                            <img id="star-5" src="images/empty_star.png" alt="star" class="empty-selector-star" onmouseover="selectStars(5, false)" onmouseout="unhoverStars()" onclick="selectStars(5,
Rekli smo 15 evenata smanjiti na 3 - event delegation princip, nešto ovako:
```
const starsWrapper = document.getElementById('review-rating-2');
starsWrapper.addEventListener('mouseover', (event) => {...
```

2024-07-04 14:08 UTC, ante-pesorda commented on tv_shows/index.js
> +]
Počistit i preimenovat

2024-07-04 14:08 UTC, ante-pesorda commented on tv_shows/index.js
> +        renderReviewList();
Kod dodavanja i brisanja nam se uvijek sve rerendera, a to želimo malo optimizirat

2024-07-04 14:08 UTC, ante-pesorda commented on tv_shows/index.js
> +    if (!reviewTextValue || starsSelected <= 0) {
alert()

2024-07-05 15:31 UTC, ante-pesorda requested changes
Zaboravili smo prokomentirat responzivnost.
Bi li još samo ovo pofiksao, pa onda možemo mergeat?

2024-07-05 15:31 UTC, ante-pesorda commented on tv_shows/index.html
> +        <link rel="stylesheet" href="styles.css">
```suggestion
        <link rel="stylesheet" href="styles.css">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
```

2024-07-05 15:31 UTC, ante-pesorda commented on tv_shows/styles.css
> +    width: 60%;
Containere najčešće ovako nekako stiliziramo umjesto u postotcima
```suggestion
    width: 920px;
    max-width: 100%;
    padding: 12px;
```

2024-07-05 16:56 UTC, mominik15 commented
Commitao sam i to 😄

2024-07-07 13:21 UTC, ante-pesorda approved these changes
🔥

2024-07-07 15:27 UTC, mominik15 commented
@ante-pesorda nice catch, ubacio sam provjeru za to :)

2024-07-07 16:51 UTC, ante-pesorda commented
🔥 
@mominik15 slobodno smergeaš

2024-07-08 18:35 UTC, mominik15 commented
@ante-pesorda ne dopusta mi da mergam :(
<img width="637" alt="Screenshot 2024-07-08 at 20 34 53" src="https://github.com/infinum-academy/js-react-academy-2024-mominik15/assets/173944928/06f76848-07ee-4790-a76f-b5677e230a1b">

2024-07-08 19:02 UTC, merged