Homework 3
infinum-academy/js-react-academy-2024-mominik15 pull request #3
Opened 2024-07-11 08:01 UTC by mominik15

For now, I implemented tasks 1 and 2. Testing is not done yet.

I will have a couple of questions about CSS (as usual):
- is sidebar implementation fine? resizing the screen breaks widths a little bit but works after reload
- when listing all shows, how can I get a grid layout the best? should I just choose a fixed width for each card and based on width screen determine the number of columns?

2024-07-12 16:42 UTC, ante-pesorda commented
@mominik15 je li ti sve pushano gore? Krenuo bacit review, pa mi puca

2024-07-12 16:44 UTC, ante-pesorda requested changes
Imali sync u uredu, malo prokomentirali dizajn i CSS positioning, solidno je radilo.
Još dodati testove.
Trenutno mi puca aplikacija, pa mi slobodno vratiš kad proradi

2024-07-13 16:28 UTC, mominik15 commented
@ante-pesorda sad bi sve trebalo biti gore. Dakle prva tri taska su rijesena (ne stignem nazalost 4 kak se spada obaviti, iako sam vidio da dosta ljudi preporucuje Route).
Prepravio sam CSS kako smo bili pricali, rijesio sam ovaj problem da se app ne ucitava na prvu i ubacio testove.

2024-07-14 20:02 UTC, ante-pesorda approved these changes
> ne stignem nazalost 4 kak se spada obaviti, iako sam vidio da dosta ljudi preporucuje Route

Ovdje misliš na 4.A, ono redirectanje?
Ima više načina, što za klijentske što za serverske komponente.
Možda ovako nešto?
```
// pages/your-page.js
import { useEffect } from 'react';
import { useRouter } from 'next/router';

export default function YourPage() {
  const router = useRouter();

  useEffect(() => {
    router.push('/new-destination');
  }, [router]);

  return null; // or a loading state
}
```

2024-07-15 15:57 UTC, mominik15 commented
E to sam i zaboravio implementirati, ubacim.

No zapravo mislio sam na onaj dio za higlightanje _All shows_ ili koje vec tipke na sidebaru, ovisno o tome na kojoj si ruti. Tu sam citao da neki kao preporucuju da se pokusa nekaj skombat s time Routerom. Negdje dam vidio i `useLocation`, ali to mi ne funkcionira u sidebaru jer imam problem s _useContext is undefined_ il tak nekaj errorom. Na kraju mi se cinilo da mi je kao najbolja opcija da mi sidebar komponenta prima argument kao kaj treba biti highlightano. Pa onda sidebar renderati na svakom pageu, ne na layoutu.

2024-07-15 16:41 UTC, ante-pesorda commented
> E to sam i zaboravio implementirati, ubacim.
> 
> No zapravo mislio sam na onaj dio za higlightanje _All shows_ ili koje vec tipke na sidebaru, ovisno o tome na kojoj si ruti. 
Tu sam citao da neki kao preporucuju da se pokusa nekaj skombat s time Routerom. Negdje dam vidio i `useLocation`, ali to mi ne funkcionira u sidebaru jer imam problem s _useContext is undefined_ il tak nekaj errorom. Na kraju mi se cinilo da mi je kao najbolja opcija da mi sidebar komponenta prima argument kao kaj treba biti highlightano. Pa onda sidebar renderati na svakom pageu, ne na layoutu.

@mominik15 a na to misliš. Možda da pokušaš ovako nekako to malo generičnije riješit? Hintovi - komentar ispod i Next navigation pathname.
Ali možemo sad bez ovog mergeati, samo da mi proradi
```
{/*
  save navigation items to some /date folder
  foreach data links
  check if path from current loop's element is equal to pathname
  if yes, add active class
*/}
```

2024-07-16 07:59 UTC, ante-pesorda approved these changes
Više se ne počisti textarea i zvjezdice nakon saveanja reviewa.
Ali i ovo možemo naknadno riješit.

Možemo ovo mergeat 🔥

2024-07-16 07:59 UTC, ante-pesorda commented on tv-shows/src/components/features/shows/ShowContainer/ShowContainer.tsx
> +        localStorage.setItem(`reviewList-${params.id}`, JSON.stringify(reviewList));
Ovdje smo rekli da bi baš u review upisivali showId na koji se taj review kači. Ovako bi se nakotilo previše localStorage itema.
Ali sad ćemo to zanemarit 🔥

2024-07-16 08:01 UTC, merged